
name: Check notebook kernelspec metadata

on: [push, pull_request]


jobs:
  check_kernelspec:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: check_kernelspec
        run: |
          python tests/check_kernelspec.py
